# Generated by Django 5.0.14 on 2026-02-09 16:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('kg', 'кг')], default='pcs', max_length=10, verbose_name='Единица')),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_one', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='На 1 шт (кол-во)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='core.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='core.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Норма списания',
                'verbose_name_plural': 'Нормы списания',
            },
        ),
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество (шт)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Операция производства',
                'verbose_name_plural': 'Операции производства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=10, verbose_name='Тип')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Продукция')),
                ('production_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.productionoperation', verbose_name='Операция производства')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
            },
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='uq_bom_product_material'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='core_stockm_created_a48320_idx'),
        ),
    ]
