# Generated by Django 5.0.14 on 2026-02-09 17:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='piece_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сдельная ставка (за 1 шт)'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ставка (за 1 шт)'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='pay_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Начислено'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('target_type', models.CharField(choices=[('material', 'Материал'), ('product', 'Продукция')], max_length=20, verbose_name='Тип')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=10, verbose_name='Операция')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина/комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Корректировка склада',
                'verbose_name_plural': 'Корректировки склада',
                'ordering': ['-created_at'],
            },
        ),
    ]
