# Generated by Django 5.0.14 on 2026-02-09 18:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создана')),
                ('name', models.CharField(max_length=120, verbose_name='Название/номер партии')),
                ('planned_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='План (шт)')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В работе'), ('done', 'Готово'), ('canceled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.batch', verbose_name='Партия'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'created_at'], name='core_batch_status_11ba84_idx'),
        ),
    ]
